# Frontend Dockerfile
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm config set strict-ssl false
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Expose the port
EXPOSE 3000

# Command to run the React app
CMD ["npm", "start"]