version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMO_ENDPOINT=http://local-dynamodb:8000
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - local-dynamodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    env_file:
      - .env

  local-dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8002:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data: