service: metadocs

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
  frontendBucketName: ${self:provider.stage}-metadocs-frontend

functions:
  backend:
    handler: backend/src/main.app  # Ensure this points to your FastAPI ASGI app instance
    events:
      - lambdaUrl:  # Corrected to lambdaUrl
          method: ANY
          path: /api

resources:
  Resources:
    S3BucketFrontend:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.frontendBucketName}
        WebsiteConfiguration:  # Configures S3 as a static website
          IndexDocument: index.html
          ErrorDocument: index.html

    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3BucketFrontend
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Join ['', ['arn:aws:s3:::', !Ref S3BucketFrontend, '/*']]

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt S3BucketFrontend.DomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:eu-central-1:514170698941:certificate/dc8a328a-a1f0-4600-887b-c4052849a5a6
            SslSupportMethod: sni-only
          Aliases:
            - app.metadocs.co  # Your custom domain name

  Outputs:
    S3BucketFrontend:
      Value: !Ref S3BucketFrontend
      Export:
        Name: ${self:service}-${self:provider.stage}-frontend-bucket

hooks:
  after:deploy:deploy:
    - npx --prefix ./frontend run build  # Builds the frontend (assuming a standard npm build script)
    - aws s3 sync ./frontend/build s3://${self:custom.frontendBucketName}/ --delete