service: metadocs

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  stage: ${opt:stage, 'dev'}  # Default to 'dev' if not provided
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-users
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-domains
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-domains/index/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-domain-memberships
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-domain-memberships/index/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-invitations
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-invitations/index/*

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
  pythonRequirements:
    dockerizePip: true
    usePoetry: true
    # noDeploy:
    #   - boto3
    #   - botocore
  frontendBucketName: ${self:provider.stage}-metadocs-frontend
  domainName: ${self:custom.domainNames.${self:provider.stage}, '${self:provider.stage}.app.metadocs.co'}
  domainNames:
    prod: app.metadocs.co

package:
  exclude:
    - frontend/**
    - node_modules/**
    - .git/**
    - .vscode/**
    - tests/**
    - README.md
    - .env

  include:
    - backend/**

functions:
  backend:
    handler: backend/src/main.handler
    events:
      - http:  # For local development with serverless-offline
          path: api/{proxy+}
          method: ANY
          cors: true
    environment:
      BUCKET_NAME: ${self:custom.frontendBucketName}
      AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
      API_AUDIENCE: ${env:API_AUDIENCE}
      USERS_TABLE: ${self:provider.stage}-users
      DOMAINS_TABLE: ${self:provider.stage}-domains
      DOMAIN_MEMBERSHIPS_TABLE: ${self:provider.stage}-domain-memberships
      INVITATIONS_TABLE: ${self:provider.stage}-invitations

resources:
  Resources:
    BackendLambdaPermission:
      Type: AWS::Lambda::Url
      Properties:
        TargetFunctionArn: !GetAtt BackendLambdaFunction.Arn
        AuthType: NONE  # No authentication (public URL)

    S3BucketFrontend:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.frontendBucketName}
        # No public access allowed; use CloudFront OAC to access content

    CloudFrontOriginAccessControl:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: "${self:provider.stage}-metadocs-OAC"
          OriginAccessControlOriginType: "s3"
          SigningBehavior: "always"
          SigningProtocol: "sigv4"

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt S3BucketFrontend.DomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: !Ref CloudFrontOriginAccessControl  # Use OAC to access S3
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:eu-central-1:514170698941:certificate/75a2585c-4c21-42ec-9713-3537db142e72
            SslSupportMethod: sni-only
          Aliases:
            - ${self:custom.domainName}

  # DynamoDB Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DomainsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DomainsTable
        AttributeDefinitions:
          - AttributeName: DomainId
            AttributeType: S
          - AttributeName: OwnerUserId
            AttributeType: S
        KeySchema:
          - AttributeName: DomainId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: OwnerUserIdIndex
            KeySchema:
              - AttributeName: OwnerUserId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    DomainMembershipsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-DomainMembershipsTable
        AttributeDefinitions:
          - AttributeName: DomainId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: DomainId
            KeyType: HASH
          - AttributeName: UserId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: UserId
                KeyType: HASH
              - AttributeName: DomainId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    InvitationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InvitationsTable
        AttributeDefinitions:
          - AttributeName: InvitationId
            AttributeType: S
          - AttributeName: InviteeEmail
            AttributeType: S
        KeySchema:
          - AttributeName: InvitationId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: InviteeEmailIndex
            KeySchema:
              - AttributeName: InviteeEmail
                KeyType: HASH
            Projection:
              ProjectionType: ALL

  Outputs:
    S3BucketFrontend:
      Value: !Ref S3BucketFrontend
      Export:
        Name: ${self:service}-${self:provider.stage}-frontend-bucket

    UsersTableName:
      Value: !Ref UsersTable
      Export:
        Name: ${self:service}-${self:provider.stage}-UsersTable

    DomainsTableName:
      Value: !Ref DomainsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-DomainsTable

    DomainMembershipsTableName:
      Value: !Ref DomainMembershipsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-DomainMembershipsTable

    InvitationsTableName:
      Value: !Ref InvitationsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-InvitationsTable